/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import java.util.*;
import otc.analysis.*;

@SuppressWarnings("nls")
public final class AAttrList extends PAttrList
{
    private final LinkedList<PType> _type_ = new LinkedList<PType>();

    public AAttrList()
    {
        // Constructor
    }

    public AAttrList(
        @SuppressWarnings("hiding") List<PType> _type_)
    {
        // Constructor
        setType(_type_);

    }

    @Override
    public Object clone()
    {
        return new AAttrList(
            cloneList(this._type_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttrList(this);
    }

    public LinkedList<PType> getType()
    {
        return this._type_;
    }

    public void setType(List<PType> list)
    {
        this._type_.clear();
        this._type_.addAll(list);
        for(PType e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PType> i = this._type_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PType) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
