/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ADateListItemTypedList extends PTypedList
{
    private TTDate _tDate_;
    private PTypedListTail _typedListTail_;

    public ADateListItemTypedList()
    {
        // Constructor
    }

    public ADateListItemTypedList(
        @SuppressWarnings("hiding") TTDate _tDate_,
        @SuppressWarnings("hiding") PTypedListTail _typedListTail_)
    {
        // Constructor
        setTDate(_tDate_);

        setTypedListTail(_typedListTail_);

    }

    @Override
    public Object clone()
    {
        return new ADateListItemTypedList(
            cloneNode(this._tDate_),
            cloneNode(this._typedListTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateListItemTypedList(this);
    }

    public TTDate getTDate()
    {
        return this._tDate_;
    }

    public void setTDate(TTDate node)
    {
        if(this._tDate_ != null)
        {
            this._tDate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDate_ = node;
    }

    public PTypedListTail getTypedListTail()
    {
        return this._typedListTail_;
    }

    public void setTypedListTail(PTypedListTail node)
    {
        if(this._typedListTail_ != null)
        {
            this._typedListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedListTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tDate_)
            + toString(this._typedListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tDate_ == child)
        {
            this._tDate_ = null;
            return;
        }

        if(this._typedListTail_ == child)
        {
            this._typedListTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tDate_ == oldChild)
        {
            setTDate((TTDate) newChild);
            return;
        }

        if(this._typedListTail_ == oldChild)
        {
            setTypedListTail((PTypedListTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
