/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ADaysListItemTypedList extends PTypedList
{
    private TTDay _tDay_;
    private PTypedList _typedList_;

    public ADaysListItemTypedList()
    {
        // Constructor
    }

    public ADaysListItemTypedList(
        @SuppressWarnings("hiding") TTDay _tDay_,
        @SuppressWarnings("hiding") PTypedList _typedList_)
    {
        // Constructor
        setTDay(_tDay_);

        setTypedList(_typedList_);

    }

    @Override
    public Object clone()
    {
        return new ADaysListItemTypedList(
            cloneNode(this._tDay_),
            cloneNode(this._typedList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADaysListItemTypedList(this);
    }

    public TTDay getTDay()
    {
        return this._tDay_;
    }

    public void setTDay(TTDay node)
    {
        if(this._tDay_ != null)
        {
            this._tDay_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDay_ = node;
    }

    public PTypedList getTypedList()
    {
        return this._typedList_;
    }

    public void setTypedList(PTypedList node)
    {
        if(this._typedList_ != null)
        {
            this._typedList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tDay_)
            + toString(this._typedList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tDay_ == child)
        {
            this._tDay_ = null;
            return;
        }

        if(this._typedList_ == child)
        {
            this._typedList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tDay_ == oldChild)
        {
            setTDay((TTDay) newChild);
            return;
        }

        if(this._typedList_ == oldChild)
        {
            setTypedList((PTypedList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
