/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ADependenciesList extends PDependenciesList
{
    private TTGroupFile _tGroupFile_;
    private PDependenciesTail _dependenciesTail_;

    public ADependenciesList()
    {
        // Constructor
    }

    public ADependenciesList(
        @SuppressWarnings("hiding") TTGroupFile _tGroupFile_,
        @SuppressWarnings("hiding") PDependenciesTail _dependenciesTail_)
    {
        // Constructor
        setTGroupFile(_tGroupFile_);

        setDependenciesTail(_dependenciesTail_);

    }

    @Override
    public Object clone()
    {
        return new ADependenciesList(
            cloneNode(this._tGroupFile_),
            cloneNode(this._dependenciesTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADependenciesList(this);
    }

    public TTGroupFile getTGroupFile()
    {
        return this._tGroupFile_;
    }

    public void setTGroupFile(TTGroupFile node)
    {
        if(this._tGroupFile_ != null)
        {
            this._tGroupFile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tGroupFile_ = node;
    }

    public PDependenciesTail getDependenciesTail()
    {
        return this._dependenciesTail_;
    }

    public void setDependenciesTail(PDependenciesTail node)
    {
        if(this._dependenciesTail_ != null)
        {
            this._dependenciesTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dependenciesTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tGroupFile_)
            + toString(this._dependenciesTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tGroupFile_ == child)
        {
            this._tGroupFile_ = null;
            return;
        }

        if(this._dependenciesTail_ == child)
        {
            this._dependenciesTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tGroupFile_ == oldChild)
        {
            setTGroupFile((TTGroupFile) newChild);
            return;
        }

        if(this._dependenciesTail_ == oldChild)
        {
            setDependenciesTail((PDependenciesTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
