/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AForeachMemberComputation extends PComputation
{
    private TTIdentifier _name_;
    private TTIdentifier _sequencename_;
    private PComputation _computation_;

    public AForeachMemberComputation()
    {
        // Constructor
    }

    public AForeachMemberComputation(
        @SuppressWarnings("hiding") TTIdentifier _name_,
        @SuppressWarnings("hiding") TTIdentifier _sequencename_,
        @SuppressWarnings("hiding") PComputation _computation_)
    {
        // Constructor
        setName(_name_);

        setSequencename(_sequencename_);

        setComputation(_computation_);

    }

    @Override
    public Object clone()
    {
        return new AForeachMemberComputation(
            cloneNode(this._name_),
            cloneNode(this._sequencename_),
            cloneNode(this._computation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForeachMemberComputation(this);
    }

    public TTIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TTIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TTIdentifier getSequencename()
    {
        return this._sequencename_;
    }

    public void setSequencename(TTIdentifier node)
    {
        if(this._sequencename_ != null)
        {
            this._sequencename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sequencename_ = node;
    }

    public PComputation getComputation()
    {
        return this._computation_;
    }

    public void setComputation(PComputation node)
    {
        if(this._computation_ != null)
        {
            this._computation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._computation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._sequencename_)
            + toString(this._computation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._sequencename_ == child)
        {
            this._sequencename_ = null;
            return;
        }

        if(this._computation_ == child)
        {
            this._computation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TTIdentifier) newChild);
            return;
        }

        if(this._sequencename_ == oldChild)
        {
            setSequencename((TTIdentifier) newChild);
            return;
        }

        if(this._computation_ == oldChild)
        {
            setComputation((PComputation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
