/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AForeachComputation extends PComputation
{
    private PActor _actor_;
    private TTIdentifier _tIdentifier_;
    private PComputation _computation_;

    public AForeachComputation()
    {
        // Constructor
    }

    public AForeachComputation(
        @SuppressWarnings("hiding") PActor _actor_,
        @SuppressWarnings("hiding") TTIdentifier _tIdentifier_,
        @SuppressWarnings("hiding") PComputation _computation_)
    {
        // Constructor
        setActor(_actor_);

        setTIdentifier(_tIdentifier_);

        setComputation(_computation_);

    }

    @Override
    public Object clone()
    {
        return new AForeachComputation(
            cloneNode(this._actor_),
            cloneNode(this._tIdentifier_),
            cloneNode(this._computation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForeachComputation(this);
    }

    public PActor getActor()
    {
        return this._actor_;
    }

    public void setActor(PActor node)
    {
        if(this._actor_ != null)
        {
            this._actor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actor_ = node;
    }

    public TTIdentifier getTIdentifier()
    {
        return this._tIdentifier_;
    }

    public void setTIdentifier(TTIdentifier node)
    {
        if(this._tIdentifier_ != null)
        {
            this._tIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tIdentifier_ = node;
    }

    public PComputation getComputation()
    {
        return this._computation_;
    }

    public void setComputation(PComputation node)
    {
        if(this._computation_ != null)
        {
            this._computation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._computation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actor_)
            + toString(this._tIdentifier_)
            + toString(this._computation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actor_ == child)
        {
            this._actor_ = null;
            return;
        }

        if(this._tIdentifier_ == child)
        {
            this._tIdentifier_ = null;
            return;
        }

        if(this._computation_ == child)
        {
            this._computation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actor_ == oldChild)
        {
            setActor((PActor) newChild);
            return;
        }

        if(this._tIdentifier_ == oldChild)
        {
            setTIdentifier((TTIdentifier) newChild);
            return;
        }

        if(this._computation_ == oldChild)
        {
            setComputation((PComputation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
