/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AGroupDefinitions extends PGroupDefinitions
{
    private PTypedName _typedName_;
    private PTypedList _typedList_;

    public AGroupDefinitions()
    {
        // Constructor
    }

    public AGroupDefinitions(
        @SuppressWarnings("hiding") PTypedName _typedName_,
        @SuppressWarnings("hiding") PTypedList _typedList_)
    {
        // Constructor
        setTypedName(_typedName_);

        setTypedList(_typedList_);

    }

    @Override
    public Object clone()
    {
        return new AGroupDefinitions(
            cloneNode(this._typedName_),
            cloneNode(this._typedList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupDefinitions(this);
    }

    public PTypedName getTypedName()
    {
        return this._typedName_;
    }

    public void setTypedName(PTypedName node)
    {
        if(this._typedName_ != null)
        {
            this._typedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedName_ = node;
    }

    public PTypedList getTypedList()
    {
        return this._typedList_;
    }

    public void setTypedList(PTypedList node)
    {
        if(this._typedList_ != null)
        {
            this._typedList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typedName_)
            + toString(this._typedList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typedName_ == child)
        {
            this._typedName_ = null;
            return;
        }

        if(this._typedList_ == child)
        {
            this._typedList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typedName_ == oldChild)
        {
            setTypedName((PTypedName) newChild);
            return;
        }

        if(this._typedList_ == oldChild)
        {
            setTypedList((PTypedList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
