/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AMaleListItemTypedList extends PTypedList
{
    private TTMale _tMale_;
    private PTypedList _typedList_;

    public AMaleListItemTypedList()
    {
        // Constructor
    }

    public AMaleListItemTypedList(
        @SuppressWarnings("hiding") TTMale _tMale_,
        @SuppressWarnings("hiding") PTypedList _typedList_)
    {
        // Constructor
        setTMale(_tMale_);

        setTypedList(_typedList_);

    }

    @Override
    public Object clone()
    {
        return new AMaleListItemTypedList(
            cloneNode(this._tMale_),
            cloneNode(this._typedList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaleListItemTypedList(this);
    }

    public TTMale getTMale()
    {
        return this._tMale_;
    }

    public void setTMale(TTMale node)
    {
        if(this._tMale_ != null)
        {
            this._tMale_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tMale_ = node;
    }

    public PTypedList getTypedList()
    {
        return this._typedList_;
    }

    public void setTypedList(PTypedList node)
    {
        if(this._typedList_ != null)
        {
            this._typedList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tMale_)
            + toString(this._typedList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tMale_ == child)
        {
            this._tMale_ = null;
            return;
        }

        if(this._typedList_ == child)
        {
            this._typedList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tMale_ == oldChild)
        {
            setTMale((TTMale) newChild);
            return;
        }

        if(this._typedList_ == oldChild)
        {
            setTypedList((PTypedList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
