/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AMonthsType extends PType
{
    private TTMonthsType _tMonthsType_;

    public AMonthsType()
    {
        // Constructor
    }

    public AMonthsType(
        @SuppressWarnings("hiding") TTMonthsType _tMonthsType_)
    {
        // Constructor
        setTMonthsType(_tMonthsType_);

    }

    @Override
    public Object clone()
    {
        return new AMonthsType(
            cloneNode(this._tMonthsType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMonthsType(this);
    }

    public TTMonthsType getTMonthsType()
    {
        return this._tMonthsType_;
    }

    public void setTMonthsType(TTMonthsType node)
    {
        if(this._tMonthsType_ != null)
        {
            this._tMonthsType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tMonthsType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tMonthsType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tMonthsType_ == child)
        {
            this._tMonthsType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tMonthsType_ == oldChild)
        {
            setTMonthsType((TTMonthsType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
