/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ANoparamEventItem extends PEventItem
{
    private TTIdentifier _tIdentifier_;

    public ANoparamEventItem()
    {
        // Constructor
    }

    public ANoparamEventItem(
        @SuppressWarnings("hiding") TTIdentifier _tIdentifier_)
    {
        // Constructor
        setTIdentifier(_tIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new ANoparamEventItem(
            cloneNode(this._tIdentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoparamEventItem(this);
    }

    public TTIdentifier getTIdentifier()
    {
        return this._tIdentifier_;
    }

    public void setTIdentifier(TTIdentifier node)
    {
        if(this._tIdentifier_ != null)
        {
            this._tIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tIdentifier_ == child)
        {
            this._tIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tIdentifier_ == oldChild)
        {
            setTIdentifier((TTIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
