/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class APatientActor extends PActor
{
    private TTPatientType _tPatientType_;

    public APatientActor()
    {
        // Constructor
    }

    public APatientActor(
        @SuppressWarnings("hiding") TTPatientType _tPatientType_)
    {
        // Constructor
        setTPatientType(_tPatientType_);

    }

    @Override
    public Object clone()
    {
        return new APatientActor(
            cloneNode(this._tPatientType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPatientActor(this);
    }

    public TTPatientType getTPatientType()
    {
        return this._tPatientType_;
    }

    public void setTPatientType(TTPatientType node)
    {
        if(this._tPatientType_ != null)
        {
            this._tPatientType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPatientType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tPatientType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tPatientType_ == child)
        {
            this._tPatientType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tPatientType_ == oldChild)
        {
            setTPatientType((TTPatientType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
