/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import java.util.*;
import otc.analysis.*;

@SuppressWarnings("nls")
public final class APermutationSequenceItem extends PSequenceItem
{
    private final LinkedList<PEventItem> _eventItem_ = new LinkedList<PEventItem>();

    public APermutationSequenceItem()
    {
        // Constructor
    }

    public APermutationSequenceItem(
        @SuppressWarnings("hiding") List<PEventItem> _eventItem_)
    {
        // Constructor
        setEventItem(_eventItem_);

    }

    @Override
    public Object clone()
    {
        return new APermutationSequenceItem(
            cloneList(this._eventItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPermutationSequenceItem(this);
    }

    public LinkedList<PEventItem> getEventItem()
    {
        return this._eventItem_;
    }

    public void setEventItem(List<PEventItem> list)
    {
        this._eventItem_.clear();
        this._eventItem_.addAll(list);
        for(PEventItem e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eventItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eventItem_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PEventItem> i = this._eventItem_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PEventItem) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
