/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import java.util.*;
import otc.analysis.*;

@SuppressWarnings("nls")
public final class ASequence extends PSequence
{
    private final LinkedList<PSequenceItem> _sequenceItem_ = new LinkedList<PSequenceItem>();

    public ASequence()
    {
        // Constructor
    }

    public ASequence(
        @SuppressWarnings("hiding") List<PSequenceItem> _sequenceItem_)
    {
        // Constructor
        setSequenceItem(_sequenceItem_);

    }

    @Override
    public Object clone()
    {
        return new ASequence(
            cloneList(this._sequenceItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequence(this);
    }

    public LinkedList<PSequenceItem> getSequenceItem()
    {
        return this._sequenceItem_;
    }

    public void setSequenceItem(List<PSequenceItem> list)
    {
        this._sequenceItem_.clear();
        this._sequenceItem_.addAll(list);
        for(PSequenceItem e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sequenceItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sequenceItem_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PSequenceItem> i = this._sequenceItem_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSequenceItem) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
