/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ASequenceType extends PType
{
    private TTSequenceType _tSequenceType_;

    public ASequenceType()
    {
        // Constructor
    }

    public ASequenceType(
        @SuppressWarnings("hiding") TTSequenceType _tSequenceType_)
    {
        // Constructor
        setTSequenceType(_tSequenceType_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceType(
            cloneNode(this._tSequenceType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceType(this);
    }

    public TTSequenceType getTSequenceType()
    {
        return this._tSequenceType_;
    }

    public void setTSequenceType(TTSequenceType node)
    {
        if(this._tSequenceType_ != null)
        {
            this._tSequenceType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSequenceType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tSequenceType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tSequenceType_ == child)
        {
            this._tSequenceType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tSequenceType_ == oldChild)
        {
            setTSequenceType((TTSequenceType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
