/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ASexType extends PType
{
    private TTSexType _tSexType_;

    public ASexType()
    {
        // Constructor
    }

    public ASexType(
        @SuppressWarnings("hiding") TTSexType _tSexType_)
    {
        // Constructor
        setTSexType(_tSexType_);

    }

    @Override
    public Object clone()
    {
        return new ASexType(
            cloneNode(this._tSexType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASexType(this);
    }

    public TTSexType getTSexType()
    {
        return this._tSexType_;
    }

    public void setTSexType(TTSexType node)
    {
        if(this._tSexType_ != null)
        {
            this._tSexType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSexType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tSexType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tSexType_ == child)
        {
            this._tSexType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tSexType_ == oldChild)
        {
            setTSexType((TTSexType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
