/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class ATableComputation extends PComputation
{
    private TTIdentifier _tIdentifier_;
    private PActor _actor_;
    private PType _type_;

    public ATableComputation()
    {
        // Constructor
    }

    public ATableComputation(
        @SuppressWarnings("hiding") TTIdentifier _tIdentifier_,
        @SuppressWarnings("hiding") PActor _actor_,
        @SuppressWarnings("hiding") PType _type_)
    {
        // Constructor
        setTIdentifier(_tIdentifier_);

        setActor(_actor_);

        setType(_type_);

    }

    @Override
    public Object clone()
    {
        return new ATableComputation(
            cloneNode(this._tIdentifier_),
            cloneNode(this._actor_),
            cloneNode(this._type_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATableComputation(this);
    }

    public TTIdentifier getTIdentifier()
    {
        return this._tIdentifier_;
    }

    public void setTIdentifier(TTIdentifier node)
    {
        if(this._tIdentifier_ != null)
        {
            this._tIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tIdentifier_ = node;
    }

    public PActor getActor()
    {
        return this._actor_;
    }

    public void setActor(PActor node)
    {
        if(this._actor_ != null)
        {
            this._actor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actor_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tIdentifier_)
            + toString(this._actor_)
            + toString(this._type_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tIdentifier_ == child)
        {
            this._tIdentifier_ = null;
            return;
        }

        if(this._actor_ == child)
        {
            this._actor_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tIdentifier_ == oldChild)
        {
            setTIdentifier((TTIdentifier) newChild);
            return;
        }

        if(this._actor_ == oldChild)
        {
            setActor((PActor) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
