/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class AYearListItemTypedList extends PTypedList
{
    private TTYear _tYear_;
    private PTypedListTail _typedListTail_;

    public AYearListItemTypedList()
    {
        // Constructor
    }

    public AYearListItemTypedList(
        @SuppressWarnings("hiding") TTYear _tYear_,
        @SuppressWarnings("hiding") PTypedListTail _typedListTail_)
    {
        // Constructor
        setTYear(_tYear_);

        setTypedListTail(_typedListTail_);

    }

    @Override
    public Object clone()
    {
        return new AYearListItemTypedList(
            cloneNode(this._tYear_),
            cloneNode(this._typedListTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAYearListItemTypedList(this);
    }

    public TTYear getTYear()
    {
        return this._tYear_;
    }

    public void setTYear(TTYear node)
    {
        if(this._tYear_ != null)
        {
            this._tYear_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tYear_ = node;
    }

    public PTypedListTail getTypedListTail()
    {
        return this._typedListTail_;
    }

    public void setTypedListTail(PTypedListTail node)
    {
        if(this._typedListTail_ != null)
        {
            this._typedListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedListTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tYear_)
            + toString(this._typedListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tYear_ == child)
        {
            this._tYear_ = null;
            return;
        }

        if(this._typedListTail_ == child)
        {
            this._typedListTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tYear_ == oldChild)
        {
            setTYear((TTYear) newChild);
            return;
        }

        if(this._typedListTail_ == oldChild)
        {
            setTypedListTail((PTypedListTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
