/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTBirthyearType extends Token
{
    public TTBirthyearType()
    {
        super.setText("Birthyear");
    }

    public TTBirthyearType(int line, int pos)
    {
        super.setText("Birthyear");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTBirthyearType(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTBirthyearType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTBirthyearType text.");
    }
}
