/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTDiagnosisType extends Token
{
    public TTDiagnosisType()
    {
        super.setText("Diagnosis");
    }

    public TTDiagnosisType(int line, int pos)
    {
        super.setText("Diagnosis");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTDiagnosisType(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTDiagnosisType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTDiagnosisType text.");
    }
}
