/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTElement extends Token
{
    public TTElement()
    {
        super.setText("element");
    }

    public TTElement(int line, int pos)
    {
        super.setText("element");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTElement(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTElement(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTElement text.");
    }
}
