/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTEnd extends Token
{
    public TTEnd()
    {
        super.setText("end");
    }

    public TTEnd(int line, int pos)
    {
        super.setText("end");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTEnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTEnd text.");
    }
}
