/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTGroup extends Token
{
    public TTGroup()
    {
        super.setText("group");
    }

    public TTGroup(int line, int pos)
    {
        super.setText("group");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTGroup(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTGroup(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTGroup text.");
    }
}
