/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTLengthof extends Token
{
    public TTLengthof()
    {
        super.setText("length of");
    }

    public TTLengthof(int line, int pos)
    {
        super.setText("length of");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTLengthof(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTLengthof(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTLengthof text.");
    }
}
