/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTLike extends Token
{
    public TTLike()
    {
        super.setText("like");
    }

    public TTLike(int line, int pos)
    {
        super.setText("like");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTLike(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTLike(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTLike text.");
    }
}
