/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTNative extends Token
{
    public TTNative()
    {
        super.setText("native");
    }

    public TTNative(int line, int pos)
    {
        super.setText("native");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTNative(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTNative(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTNative text.");
    }
}
