/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTPeriod extends Token
{
    public TTPeriod()
    {
        super.setText("period is");
    }

    public TTPeriod(int line, int pos)
    {
        super.setText("period is");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPeriod(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPeriod(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPeriod text.");
    }
}
