/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTPopulation extends Token
{
    public TTPopulation()
    {
        super.setText("population is");
    }

    public TTPopulation(int line, int pos)
    {
        super.setText("population is");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPopulation(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPopulation(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPopulation text.");
    }
}
