/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTSequences extends Token
{
    public TTSequences()
    {
        super.setText("sequences");
    }

    public TTSequences(int line, int pos)
    {
        super.setText("sequences");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTSequences(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTSequences(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTSequences text.");
    }
}
