/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTSequence extends Token
{
    public TTSequence()
    {
        super.setText("sequence");
    }

    public TTSequence(int line, int pos)
    {
        super.setText("sequence");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTSequence(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTSequence(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTSequence text.");
    }
}
