/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTSexType extends Token
{
    public TTSexType()
    {
        super.setText("Sex");
    }

    public TTSexType(int line, int pos)
    {
        super.setText("Sex");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTSexType(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTSexType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTSexType text.");
    }
}
