/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTTable extends Token
{
    public TTTable()
    {
        super.setText("table");
    }

    public TTTable(int line, int pos)
    {
        super.setText("table");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTTable(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTTable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTTable text.");
    }
}
