/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTTimeType extends Token
{
    public TTTimeType()
    {
        super.setText("Times");
    }

    public TTTimeType(int line, int pos)
    {
        super.setText("Times");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTTimeType(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTTimeType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTTimeType text.");
    }
}
