/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTTo extends Token
{
    public TTTo()
    {
        super.setText("to");
    }

    public TTTo(int line, int pos)
    {
        super.setText("to");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTTo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTTo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTTo text.");
    }
}
