/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTUse extends Token
{
    public TTUse()
    {
        super.setText("use");
    }

    public TTUse(int line, int pos)
    {
        super.setText("use");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTUse(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTUse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTUse text.");
    }
}
