/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.node;

import otc.analysis.*;

@SuppressWarnings("nls")
public final class TTWhere extends Token
{
    public TTWhere()
    {
        super.setText("where");
    }

    public TTWhere(int line, int pos)
    {
        super.setText("where");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTWhere(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTWhere(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTWhere text.");
    }
}
