/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.analysis;

import otc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAHeader(AHeader node);
    void caseAParameters(AParameters node);
    void caseAParametersTail(AParametersTail node);
    void caseAIdType(AIdType node);
    void caseASexType(ASexType node);
    void caseABirthyearType(ABirthyearType node);
    void caseADiagnosisType(ADiagnosisType node);
    void caseAPostalcodeType(APostalcodeType node);
    void caseAYearsType(AYearsType node);
    void caseAMonthsType(AMonthsType node);
    void caseADaysType(ADaysType node);
    void caseADateType(ADateType node);
    void caseAEventType(AEventType node);
    void caseASequenceType(ASequenceType node);
    void caseADependencies(ADependencies node);
    void caseADependenciesList(ADependenciesList node);
    void caseADependenciesTail(ADependenciesTail node);

    void caseTTScript(TTScript node);
    void caseTTBy(TTBy node);
    void caseTTOf(TTOf node);
    void caseTTTo(TTTo node);
    void caseTTIn(TTIn node);
    void caseTTUse(TTUse node);
    void caseTTGroup(TTGroup node);
    void caseTTPeriod(TTPeriod node);
    void caseTTPopulation(TTPopulation node);
    void caseTTDoctor(TTDoctor node);
    void caseTTEvents(TTEvents node);
    void caseTTForeach(TTForeach node);
    void caseTTTable(TTTable node);
    void caseTTWhere(TTWhere node);
    void caseTTPrint(TTPrint node);
    void caseTTNative(TTNative node);
    void caseTTLike(TTLike node);
    void caseTTSequence(TTSequence node);
    void caseTTSequences(TTSequences node);
    void caseTTList(TTList node);
    void caseTTBarchart(TTBarchart node);
    void caseTTSize(TTSize node);
    void caseTTMember(TTMember node);
    void caseTTCount(TTCount node);
    void caseTTTimeline(TTTimeline node);
    void caseTTIdType(TTIdType node);
    void caseTTSexType(TTSexType node);
    void caseTTBirthyearType(TTBirthyearType node);
    void caseTTDiagnosisType(TTDiagnosisType node);
    void caseTTPostalcodeType(TTPostalcodeType node);
    void caseTTYearsType(TTYearsType node);
    void caseTTMonthsType(TTMonthsType node);
    void caseTTDaysType(TTDaysType node);
    void caseTTDateType(TTDateType node);
    void caseTTEventType(TTEventType node);
    void caseTTSequenceType(TTSequenceType node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTComma(TComma node);
    void caseTTGroupFile(TTGroupFile node);
    void caseTTIdentifier(TTIdentifier node);
    void caseTTScriptName(TTScriptName node);
    void caseTTDocComment(TTDocComment node);
    void caseTEmptySpace(TEmptySpace node);
    void caseTLineComment(TLineComment node);
    void caseEOF(EOF node);
}
