/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.analysis;

import java.util.*;
import otc.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    public void caseAHeader(AHeader node)
    {
        defaultCase(node);
    }

    public void caseAParameters(AParameters node)
    {
        defaultCase(node);
    }

    public void caseAParametersTail(AParametersTail node)
    {
        defaultCase(node);
    }

    public void caseAIdType(AIdType node)
    {
        defaultCase(node);
    }

    public void caseASexType(ASexType node)
    {
        defaultCase(node);
    }

    public void caseABirthyearType(ABirthyearType node)
    {
        defaultCase(node);
    }

    public void caseADiagnosisType(ADiagnosisType node)
    {
        defaultCase(node);
    }

    public void caseAPostalcodeType(APostalcodeType node)
    {
        defaultCase(node);
    }

    public void caseAYearsType(AYearsType node)
    {
        defaultCase(node);
    }

    public void caseAMonthsType(AMonthsType node)
    {
        defaultCase(node);
    }

    public void caseADaysType(ADaysType node)
    {
        defaultCase(node);
    }

    public void caseADateType(ADateType node)
    {
        defaultCase(node);
    }

    public void caseAEventType(AEventType node)
    {
        defaultCase(node);
    }

    public void caseASequenceType(ASequenceType node)
    {
        defaultCase(node);
    }

    public void caseADependencies(ADependencies node)
    {
        defaultCase(node);
    }

    public void caseADependenciesList(ADependenciesList node)
    {
        defaultCase(node);
    }

    public void caseADependenciesTail(ADependenciesTail node)
    {
        defaultCase(node);
    }

    public void caseTTScript(TTScript node)
    {
        defaultCase(node);
    }

    public void caseTTBy(TTBy node)
    {
        defaultCase(node);
    }

    public void caseTTOf(TTOf node)
    {
        defaultCase(node);
    }

    public void caseTTTo(TTTo node)
    {
        defaultCase(node);
    }

    public void caseTTIn(TTIn node)
    {
        defaultCase(node);
    }

    public void caseTTUse(TTUse node)
    {
        defaultCase(node);
    }

    public void caseTTGroup(TTGroup node)
    {
        defaultCase(node);
    }

    public void caseTTPeriod(TTPeriod node)
    {
        defaultCase(node);
    }

    public void caseTTPopulation(TTPopulation node)
    {
        defaultCase(node);
    }

    public void caseTTDoctor(TTDoctor node)
    {
        defaultCase(node);
    }

    public void caseTTEvents(TTEvents node)
    {
        defaultCase(node);
    }

    public void caseTTForeach(TTForeach node)
    {
        defaultCase(node);
    }

    public void caseTTTable(TTTable node)
    {
        defaultCase(node);
    }

    public void caseTTWhere(TTWhere node)
    {
        defaultCase(node);
    }

    public void caseTTPrint(TTPrint node)
    {
        defaultCase(node);
    }

    public void caseTTNative(TTNative node)
    {
        defaultCase(node);
    }

    public void caseTTLike(TTLike node)
    {
        defaultCase(node);
    }

    public void caseTTSequence(TTSequence node)
    {
        defaultCase(node);
    }

    public void caseTTSequences(TTSequences node)
    {
        defaultCase(node);
    }

    public void caseTTList(TTList node)
    {
        defaultCase(node);
    }

    public void caseTTBarchart(TTBarchart node)
    {
        defaultCase(node);
    }

    public void caseTTSize(TTSize node)
    {
        defaultCase(node);
    }

    public void caseTTMember(TTMember node)
    {
        defaultCase(node);
    }

    public void caseTTCount(TTCount node)
    {
        defaultCase(node);
    }

    public void caseTTTimeline(TTTimeline node)
    {
        defaultCase(node);
    }

    public void caseTTIdType(TTIdType node)
    {
        defaultCase(node);
    }

    public void caseTTSexType(TTSexType node)
    {
        defaultCase(node);
    }

    public void caseTTBirthyearType(TTBirthyearType node)
    {
        defaultCase(node);
    }

    public void caseTTDiagnosisType(TTDiagnosisType node)
    {
        defaultCase(node);
    }

    public void caseTTPostalcodeType(TTPostalcodeType node)
    {
        defaultCase(node);
    }

    public void caseTTYearsType(TTYearsType node)
    {
        defaultCase(node);
    }

    public void caseTTMonthsType(TTMonthsType node)
    {
        defaultCase(node);
    }

    public void caseTTDaysType(TTDaysType node)
    {
        defaultCase(node);
    }

    public void caseTTDateType(TTDateType node)
    {
        defaultCase(node);
    }

    public void caseTTEventType(TTEventType node)
    {
        defaultCase(node);
    }

    public void caseTTSequenceType(TTSequenceType node)
    {
        defaultCase(node);
    }

    public void caseTLParen(TLParen node)
    {
        defaultCase(node);
    }

    public void caseTRParen(TRParen node)
    {
        defaultCase(node);
    }

    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    public void caseTTGroupFile(TTGroupFile node)
    {
        defaultCase(node);
    }

    public void caseTTIdentifier(TTIdentifier node)
    {
        defaultCase(node);
    }

    public void caseTTScriptName(TTScriptName node)
    {
        defaultCase(node);
    }

    public void caseTTDocComment(TTDocComment node)
    {
        defaultCase(node);
    }

    public void caseTEmptySpace(TEmptySpace node)
    {
        defaultCase(node);
    }

    public void caseTLineComment(TLineComment node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
