/* This file was generated by SableCC (http://www.sablecc.org/). */

package otc.lexer;

import java.io.*;
import otc.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTScript(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBy(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTOf(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTTo(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTIn(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTUse(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEnd(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNot(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTGroup(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPeriod(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPopulation(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDoctorFilter(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEvents(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTForeach(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTTable(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTWhere(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPrint(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNative(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLike(line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSequence(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTList(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBarchart(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSize(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMember(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTCount(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTTimeline(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLengthof(line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMale(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTFemale(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTElement(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTIdType(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSexType(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBirthyearType(line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPatientType(text, line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDoctorType(text, line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDiagnosisType(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPostalcodeType(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTYearsType(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMonthsType(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDaysType(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDateType(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEventType(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSequenceType(line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTHoursType(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLParen(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRParen(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquals(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLAngle(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRAngle(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLSquare(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRSquare(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRArrow(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPipe(line, pos); }
    Token new57(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTGroupFile(text, line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTStar(line, pos); }
    Token new59(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPostalcode(text, line, pos); }
    Token new60(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDate(text, line, pos); }
    Token new61(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTHour(text, line, pos); }
    Token new62(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDay(text, line, pos); }
    Token new63(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTYear(text, line, pos); }
    Token new64(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMonth(text, line, pos); }
    Token new65(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNumber(text, line, pos); }
    Token new66(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTIdentifier(text, line, pos); }
    Token new67(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTScriptName(text, line, pos); }
    Token new68(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDocComment(text, line, pos); }
    Token new69(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmptySpace(text, line, pos); }
    Token new70(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLineComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {40, 40, 5}, {41, 41, 6}, {42, 42, 7}, {44, 44, 8}, {45, 45, 9}, {47, 47, 10}, {48, 57, 11}, {58, 58, 12}, {60, 60, 13}, {61, 61, 14}, {62, 62, 15}, {65, 65, 16}, {66, 66, 17}, {67, 67, 16}, {68, 68, 18}, {69, 69, 19}, {70, 70, 20}, {71, 71, 16}, {72, 72, 21}, {73, 73, 22}, {74, 76, 16}, {77, 77, 23}, {78, 79, 16}, {80, 80, 24}, {81, 82, 16}, {83, 83, 25}, {84, 84, 26}, {85, 86, 16}, {87, 87, 27}, {88, 88, 16}, {89, 89, 28}, {90, 90, 16}, {91, 91, 29}, {93, 93, 30}, {97, 97, 31}, {98, 98, 32}, {99, 99, 33}, {100, 100, 34}, {101, 101, 35}, {102, 102, 36}, {103, 103, 37}, {104, 104, 31}, {105, 105, 38}, {106, 107, 31}, {108, 108, 39}, {109, 109, 40}, {110, 110, 41}, {111, 111, 42}, {112, 112, 43}, {113, 114, 31}, {115, 115, 44}, {116, 116, 45}, {117, 117, 46}, {118, 118, 31}, {119, 119, 47}, {120, 122, 31}, {123, 123, 48}, {124, 124, 49}, {125, 125, 50}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 51}, },
            {{42, 42, 52}, {47, 47, 53}, },
            {{48, 57, 54}, },
            {},
            {},
            {},
            {},
            {{46, 46, 55}, {48, 57, 56}, {65, 90, 57}, {95, 95, 58}, {97, 122, 57}, },
            {{46, 95, -18}, {97, 104, 57}, {105, 105, 59}, {106, 122, 57}, },
            {{46, 95, -18}, {97, 97, 60}, {98, 104, 57}, {105, 105, 61}, {106, 110, 57}, {111, 111, 62}, {112, 122, 57}, },
            {{46, 95, -18}, {97, 117, 57}, {118, 118, 63}, {119, 122, 57}, },
            {{46, 95, -18}, {97, 100, 57}, {101, 101, 64}, {102, 113, 57}, {114, 114, 65}, {115, 122, 57}, },
            {{46, 95, -18}, {97, 110, 57}, {111, 111, 66}, {112, 122, 57}, },
            {{46, 95, -18}, {97, 99, 57}, {100, 100, 67}, {101, 122, 57}, },
            {{46, 95, -18}, {97, 97, 68}, {98, 110, 57}, {111, 111, 69}, {112, 122, 57}, },
            {{46, 95, -18}, {97, 97, 70}, {98, 110, 57}, {111, 111, 71}, {112, 122, 57}, },
            {{46, 95, -18}, {97, 97, 72}, {98, 100, 57}, {101, 101, 73}, {102, 116, 57}, {117, 117, 74}, {118, 122, 57}, },
            {{46, 95, -18}, {97, 103, 57}, {104, 104, 75}, {105, 116, 57}, {117, 117, 76}, {118, 122, 57}, },
            {{46, 100, -22}, {101, 101, 77}, {102, 122, 57}, },
            {{46, 100, -22}, {101, 101, 78}, {102, 122, 57}, },
            {},
            {},
            {{46, 46, 55}, {48, 57, 79}, {65, 90, 80}, {95, 95, 81}, {97, 122, 80}, },
            {{46, 95, -33}, {97, 97, 82}, {98, 120, 80}, {121, 121, 83}, {122, 122, 80}, },
            {{46, 95, -33}, {97, 110, 80}, {111, 111, 84}, {112, 122, 80}, },
            {{46, 110, -35}, {111, 111, 85}, {112, 122, 80}, },
            {{46, 95, -33}, {97, 107, 80}, {108, 108, 86}, {109, 109, 80}, {110, 110, 87}, {111, 117, 80}, {118, 118, 88}, {119, 122, 80}, },
            {{46, 95, -33}, {97, 100, 80}, {101, 101, 89}, {102, 110, 80}, {111, 111, 90}, {112, 122, 80}, },
            {{46, 95, -33}, {97, 113, 80}, {114, 114, 91}, {115, 122, 80}, },
            {{46, 95, -33}, {97, 109, 80}, {110, 110, 92}, {111, 122, 80}, },
            {{46, 100, -38}, {101, 101, 93}, {102, 104, 80}, {105, 105, 94}, {106, 122, 80}, },
            {{46, 95, -33}, {97, 97, 95}, {98, 100, 80}, {101, 101, 96}, {102, 122, 80}, },
            {{46, 95, -33}, {97, 97, 97}, {98, 110, 80}, {111, 111, 98}, {112, 122, 80}, },
            {{46, 95, -33}, {97, 101, 80}, {102, 102, 99}, {103, 122, 80}, },
            {{46, 100, -38}, {101, 101, 100}, {102, 110, 80}, {111, 111, 101}, {112, 113, 80}, {114, 114, 102}, {115, 122, 80}, },
            {{46, 95, -33}, {97, 98, 80}, {99, 99, 103}, {100, 100, 80}, {101, 101, 104}, {102, 104, 80}, {105, 105, 105}, {106, 122, 80}, },
            {{46, 95, -33}, {97, 97, 106}, {98, 104, 80}, {105, 105, 107}, {106, 110, 80}, {111, 111, 108}, {112, 122, 80}, },
            {{46, 95, -33}, {97, 114, 80}, {115, 115, 109}, {116, 122, 80}, },
            {{46, 95, -33}, {97, 103, 80}, {104, 104, 110}, {105, 122, 80}, },
            {},
            {},
            {},
            {},
            {{0, 41, 111}, {42, 42, 112}, {43, 127, 111}, },
            {{0, 9, 113}, {10, 10, 114}, {11, 12, 113}, {13, 13, 115}, {14, 127, 113}, },
            {{48, 57, 116}, {58, 58, 117}, },
            {{103, 103, 118}, },
            {{46, 46, 55}, {48, 57, 119}, {65, 90, 120}, {95, 122, -18}, },
            {{46, 57, -58}, {65, 122, -18}, },
            {{46, 122, -59}, },
            {{46, 95, -59}, {97, 113, 57}, {114, 114, 121}, {115, 122, 57}, },
            {{46, 95, -59}, {97, 115, 57}, {116, 116, 122}, {117, 120, 57}, {121, 121, 123}, {122, 122, 57}, },
            {{46, 95, -59}, {97, 97, 124}, {98, 122, 57}, },
            {{46, 95, -59}, {97, 98, 57}, {99, 99, 125}, {100, 122, 57}, },
            {{46, 95, -59}, {97, 100, 57}, {101, 101, 126}, {102, 122, 57}, },
            {{46, 95, -59}, {97, 108, 57}, {109, 109, 127}, {110, 122, 57}, },
            {{46, 95, -59}, {97, 104, 57}, {105, 105, 128}, {106, 122, 57}, },
            {{46, 95, -59}, {97, 116, 57}, {117, 117, 129}, {118, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 95, -59}, {97, 107, 57}, {108, 108, 130}, {109, 122, 57}, },
            {{46, 95, -59}, {97, 109, 57}, {110, 110, 131}, {111, 122, 57}, },
            {{46, 115, -62}, {116, 116, 132}, {117, 122, 57}, },
            {{46, 95, -59}, {97, 114, 57}, {115, 115, 133}, {116, 122, 57}, },
            {{46, 115, -62}, {116, 116, 134}, {117, 122, 57}, },
            {{46, 95, -59}, {97, 112, 57}, {113, 113, 135}, {114, 119, 57}, {120, 120, 136}, {121, 122, 57}, },
            {{46, 109, -71}, {110, 110, 137}, {111, 122, 57}, },
            {{46, 116, -68}, {117, 117, 138}, {118, 122, 57}, },
            {{46, 100, -65}, {101, 101, 139}, {102, 122, 57}, },
            {{46, 95, -59}, {97, 99, 57}, {100, 100, 140}, {101, 122, 57}, },
            {{46, 95, -59}, {97, 97, 141}, {98, 122, 57}, },
            {{46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 113, -39}, {114, 114, 142}, {115, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 95, -33}, {97, 116, 80}, {117, 117, 143}, {118, 122, 80}, },
            {{46, 98, -46}, {99, 99, 144}, {100, 122, 80}, },
            {{46, 100, -38}, {101, 101, 145}, {102, 122, 80}, },
            {{46, 95, -33}, {97, 99, 80}, {100, 100, 146}, {101, 122, 80}, },
            {{46, 100, -38}, {101, 101, 147}, {102, 122, 80}, },
            {{46, 95, -33}, {97, 108, 80}, {109, 109, 148}, {110, 122, 80}, },
            {{46, 113, -39}, {114, 114, 149}, {115, 122, 80}, },
            {{46, 110, -35}, {111, 111, 150}, {112, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 109, -40}, {110, 110, 151}, {111, 122, 80}, },
            {{46, 95, -33}, {97, 106, 80}, {107, 107, 152}, {108, 114, 80}, {115, 115, 153}, {116, 122, 80}, },
            {{46, 107, -37}, {108, 108, 154}, {109, 122, 80}, },
            {{46, 108, -91}, {109, 109, 155}, {110, 122, 80}, },
            {{46, 95, -33}, {97, 115, 80}, {116, 116, 156}, {117, 122, 80}, },
            {{46, 115, -99}, {116, 116, 157}, {117, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 113, -39}, {114, 114, 158}, {115, 122, 80}, },
            {{46, 95, -33}, {97, 111, 80}, {112, 112, 159}, {113, 122, 80}, },
            {{46, 95, -33}, {97, 104, 80}, {105, 105, 160}, {106, 122, 80}, },
            {{46, 113, -39}, {114, 114, 161}, {115, 122, 80}, },
            {{46, 95, -33}, {97, 112, 80}, {113, 113, 162}, {114, 122, 80}, },
            {{46, 95, -33}, {97, 121, 80}, {122, 122, 163}, },
            {{46, 95, -33}, {97, 97, 80}, {98, 98, 164}, {99, 122, 80}, },
            {{46, 108, -91}, {109, 109, 165}, {110, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 100, -38}, {101, 101, 166}, {102, 122, 80}, },
            {{46, 100, -38}, {101, 101, 167}, {102, 122, 80}, },
            {{0, 127, -54}, },
            {{0, 41, 168}, {42, 42, 112}, {43, 46, 168}, {47, 47, 169}, {48, 127, 168}, },
            {{0, 127, -55}, },
            {{13, 13, 170}, },
            {},
            {{48, 57, 171}, },
            {{48, 57, 172}, },
            {{114, 114, 173}, },
            {{46, 122, -59}, },
            {{46, 46, 55}, {48, 57, 174}, {65, 122, -18}, },
            {{46, 115, -62}, {116, 116, 175}, {117, 122, 57}, },
            {{46, 100, -65}, {101, 101, 176}, {102, 122, 57}, },
            {{46, 114, -73}, {115, 115, 177}, {116, 122, 57}, },
            {{46, 95, -59}, {97, 102, 57}, {103, 103, 178}, {104, 122, 57}, },
            {{46, 115, -62}, {116, 116, 179}, {117, 122, 57}, },
            {{46, 109, -71}, {110, 110, 180}, {111, 122, 57}, },
            {{46, 95, -59}, {97, 97, 181}, {98, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 113, -61}, {114, 114, 182}, {115, 122, 57}, },
            {{46, 100, -65}, {101, 101, 183}, {102, 122, 57}, },
            {{46, 115, -62}, {116, 116, 184}, {117, 122, 57}, },
            {{46, 104, -67}, {105, 105, 185}, {106, 122, 57}, },
            {{46, 115, -62}, {116, 116, 186}, {117, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 116, -68}, {117, 117, 187}, {118, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 122, -59}, },
            {{46, 113, -61}, {114, 114, 188}, {115, 122, 57}, },
            {{46, 114, -73}, {115, 115, 189}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 113, -61}, {114, 114, 190}, {115, 122, 57}, },
            {{46, 98, -46}, {99, 99, 191}, {100, 122, 80}, },
            {{46, 109, -40}, {110, 110, 192}, {111, 122, 80}, },
            {{46, 115, -99}, {116, 116, 193}, {117, 122, 80}, },
            {{46, 108, -91}, {109, 109, 194}, {110, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 109, -40}, {110, 110, 195}, {111, 122, 80}, },
            {{46, 95, -33}, {97, 97, 196}, {98, 122, 80}, },
            {{46, 100, -38}, {101, 101, 197}, {102, 122, 80}, },
            {{46, 116, -86}, {117, 117, 198}, {118, 122, 80}, },
            {{46, 95, -33}, {97, 102, 80}, {103, 103, 199}, {104, 122, 80}, },
            {{46, 100, -38}, {101, 101, 200}, {102, 122, 80}, },
            {{46, 115, -99}, {116, 116, 201}, {117, 122, 80}, },
            {{46, 100, -38}, {101, 101, 202}, {102, 122, 80}, },
            {{46, 97, -108}, {98, 98, 203}, {99, 122, 80}, },
            {{46, 104, -104}, {105, 105, 204}, {106, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 104, -104}, {105, 105, 205}, {106, 122, 80}, },
            {{46, 116, -86}, {117, 117, 206}, {118, 122, 80}, },
            {{46, 109, -40}, {110, 110, 207}, {111, 122, 80}, },
            {{46, 104, -104}, {105, 105, 208}, {106, 122, 80}, },
            {{46, 116, -86}, {117, 117, 209}, {118, 122, 80}, },
            {{46, 100, -38}, {101, 101, 210}, {102, 122, 80}, },
            {{46, 107, -37}, {108, 108, 211}, {109, 122, 80}, },
            {{46, 100, -38}, {101, 101, 212}, {102, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 113, -39}, {114, 114, 213}, {115, 122, 80}, },
            {{0, 41, 214}, {42, 42, 112}, {43, 127, 214}, },
            {},
            {},
            {{45, 45, 215}, {48, 57, 216}, },
            {{48, 57, 217}, },
            {{112, 112, 218}, },
            {{46, 57, -58}, {65, 90, 219}, {95, 122, -18}, },
            {{46, 95, -59}, {97, 103, 57}, {104, 104, 220}, {105, 122, 57}, },
            {{46, 114, -73}, {115, 115, 221}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 109, -71}, {110, 110, 222}, {111, 122, 57}, },
            {{46, 95, -59}, {97, 110, 57}, {111, 111, 223}, {112, 122, 57}, },
            {{46, 115, -62}, {116, 116, 224}, {117, 122, 57}, },
            {{46, 107, -70}, {108, 108, 225}, {109, 122, 57}, },
            {{46, 114, -73}, {115, 115, 226}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 103, -177}, {104, 104, 227}, {105, 122, 57}, },
            {{46, 100, -65}, {101, 101, 228}, {102, 122, 57}, },
            {{46, 95, -59}, {97, 97, 229}, {98, 122, 57}, },
            {{46, 100, -65}, {101, 101, 230}, {102, 122, 57}, },
            {{46, 114, -73}, {115, 115, 231}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 114, -73}, {115, 115, 232}, {116, 122, 57}, },
            {{46, 103, -49}, {104, 104, 233}, {105, 122, 80}, },
            {{46, 115, -99}, {116, 116, 234}, {117, 122, 80}, },
            {{46, 110, -35}, {111, 111, 235}, {112, 122, 80}, },
            {{46, 100, -38}, {101, 101, 236}, {102, 122, 80}, },
            {{46, 115, -99}, {116, 116, 237}, {117, 122, 80}, },
            {{46, 107, -37}, {108, 108, 238}, {109, 122, 80}, },
            {{46, 95, -33}, {97, 97, 239}, {98, 122, 80}, },
            {{46, 111, -103}, {112, 112, 240}, {113, 122, 80}, },
            {{46, 115, -99}, {116, 116, 241}, {117, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 100, -38}, {101, 101, 242}, {102, 122, 80}, },
            {{46, 95, -33}, {97, 117, 80}, {118, 118, 243}, {119, 122, 80}, },
            {{46, 110, -35}, {111, 111, 244}, {112, 122, 80}, },
            {{46, 107, -37}, {108, 108, 245}, {109, 122, 80}, },
            {{46, 115, -99}, {116, 116, 246}, {117, 122, 80}, },
            {{46, 111, -103}, {112, 112, 247}, {113, 122, 80}, },
            {{46, 100, -38}, {101, 101, 248}, {102, 122, 80}, },
            {{32, 32, 249}, {46, 122, -33}, },
            {{46, 100, -38}, {101, 101, 250}, {102, 122, 80}, },
            {{46, 107, -37}, {108, 108, 251}, {109, 122, 80}, },
            {{46, 100, -38}, {101, 101, 252}, {102, 122, 80}, },
            {{0, 127, -170}, },
            {{48, 57, 253}, },
            {{48, 57, 216}, },
            {},
            {},
            {{46, 46, 55}, {48, 57, 254}, {65, 122, -18}, },
            {{46, 95, -59}, {97, 120, 57}, {121, 121, 255}, {122, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 110, -181}, {111, 111, 256}, {112, 122, 57}, },
            {{46, 113, -61}, {114, 114, 257}, {115, 122, 57}, },
            {{46, 114, -73}, {115, 115, 258}, {116, 122, 57}, },
            {{46, 100, -65}, {101, 101, 259}, {102, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 114, -73}, {115, 115, 260}, {116, 122, 57}, },
            {{46, 109, -71}, {110, 110, 261}, {111, 122, 57}, },
            {{46, 107, -70}, {108, 108, 262}, {109, 122, 57}, },
            {{46, 109, -71}, {110, 110, 263}, {111, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 122, -59}, },
            {{46, 95, -33}, {97, 97, 264}, {98, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 113, -39}, {114, 114, 265}, {115, 122, 80}, },
            {{46, 109, -40}, {110, 110, 266}, {111, 122, 80}, },
            {{46, 114, -48}, {115, 115, 267}, {116, 122, 80}, },
            {{46, 100, -38}, {101, 101, 268}, {102, 122, 80}, },
            {{46, 98, -46}, {99, 99, 269}, {100, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 103, -49}, {104, 104, 270}, {105, 122, 80}, },
            {{46, 113, -39}, {114, 114, 271}, {115, 122, 80}, },
            {{46, 100, -38}, {101, 101, 272}, {102, 122, 80}, },
            {{46, 99, -89}, {100, 100, 273}, {101, 122, 80}, },
            {{46, 95, -33}, {97, 97, 274}, {98, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 115, -99}, {116, 116, 275}, {117, 122, 80}, },
            {{46, 109, -40}, {110, 110, 276}, {111, 122, 80}, },
            {{111, 111, 277}, },
            {{46, 122, -33}, },
            {{46, 104, -104}, {105, 105, 278}, {106, 122, 80}, },
            {{46, 122, -33}, },
            {{48, 57, 279}, },
            {{46, 122, -59}, },
            {{46, 100, -65}, {101, 101, 280}, {102, 122, 57}, },
            {{46, 114, -73}, {115, 115, 281}, {116, 122, 57}, },
            {{46, 114, -73}, {115, 115, 282}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 122, -59}, },
            {{46, 122, -59}, },
            {{46, 115, -62}, {116, 116, 283}, {117, 122, 57}, },
            {{46, 57, -58}, {65, 66, 57}, {67, 67, 284}, {68, 90, 57}, {95, 122, -18}, },
            {{46, 98, -64}, {99, 99, 285}, {100, 122, 57}, },
            {{46, 113, -39}, {114, 114, 286}, {115, 122, 80}, },
            {{46, 114, -48}, {115, 115, 287}, {116, 122, 80}, },
            {{46, 115, -99}, {116, 116, 288}, {117, 122, 80}, },
            {{32, 32, 289}, {46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 103, -49}, {104, 104, 290}, {105, 122, 80}, },
            {{32, 32, 291}, {46, 122, -33}, },
            {{46, 122, -33}, },
            {{46, 122, -33}, },
            {{32, 32, 292}, {46, 122, -33}, },
            {{46, 115, -99}, {116, 116, 293}, {117, 122, 80}, },
            {{46, 122, -33}, },
            {{46, 98, -46}, {99, 99, 294}, {100, 122, 80}, },
            {{102, 102, 295}, },
            {{46, 109, -40}, {110, 110, 296}, {111, 122, 80}, },
            {{45, 45, 297}, },
            {{46, 95, -59}, {97, 97, 298}, {98, 122, 57}, },
            {{46, 104, -67}, {105, 105, 299}, {106, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 114, -73}, {115, 115, 300}, {116, 122, 57}, },
            {{46, 110, -181}, {111, 111, 301}, {112, 122, 57}, },
            {{46, 100, -65}, {101, 101, 302}, {102, 122, 57}, },
            {{46, 115, -99}, {116, 116, 303}, {117, 122, 80}, },
            {{32, 32, 304}, {46, 122, -33}, },
            {{46, 122, -33}, },
            {{97, 97, 305}, },
            {{46, 122, -33}, },
            {{111, 111, 306}, },
            {{105, 105, 307}, },
            {{46, 104, -104}, {105, 105, 308}, {106, 122, 80}, },
            {{46, 100, -38}, {101, 101, 309}, {102, 122, 80}, },
            {},
            {{46, 100, -38}, {101, 101, 310}, {102, 122, 80}, },
            {{48, 57, 311}, },
            {{46, 113, -61}, {114, 114, 312}, {115, 122, 57}, },
            {{46, 114, -73}, {115, 115, 313}, {116, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 99, -79}, {100, 100, 314}, {101, 122, 57}, },
            {{46, 122, -59}, },
            {{46, 122, -33}, },
            {{97, 97, 315}, },
            {{114, 114, 316}, },
            {{102, 102, 317}, },
            {{115, 115, 318}, },
            {{46, 110, -35}, {111, 111, 319}, {112, 122, 80}, },
            {{46, 114, -48}, {115, 115, 320}, {116, 122, 80}, },
            {{46, 122, -33}, },
            {{48, 57, 321}, },
            {{46, 122, -59}, },
            {{46, 122, -59}, },
            {{46, 100, -65}, {101, 101, 322}, {102, 122, 57}, },
            {{114, 114, 323}, },
            {{101, 101, 324}, },
            {},
            {},
            {{46, 109, -40}, {110, 110, 325}, {111, 122, 80}, },
            {{46, 122, -33}, },
            {},
            {{46, 122, -59}, },
            {{101, 101, 326}, },
            {},
            {{32, 32, 327}, {46, 122, -33}, },
            {},
            {{105, 105, 328}, },
            {{115, 115, 329}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {65, 69, 69, 69, 69, 44, 45, 58, 48, -1, -1, 65, 49, 51, 50, 52, 59, 59, 59, 59, 28, 59, 59, 27, 59, 59, 59, 59, 59, 53, 54, 66, 66, 66, 66, 66, 28, 66, 66, 66, 27, 66, 66, 66, 66, 66, 66, 66, 46, 56, 47, 55, -1, -1, 64, -1, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 30, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 66, 66, 66, 66, 1, 66, 66, 66, 66, 66, 66, 66, 66, 4, 66, 66, 66, 66, 66, 66, 2, 66, 66, 66, 66, 66, 66, 66, 66, 3, 66, 66, -1, -1, -1, 70, 70, 65, -1, -1, 67, 59, 67, 67, 67, 67, 67, 67, 67, 62, 67, 67, 62, 67, 67, 62, 67, 31, 62, 67, 67, 62, 67, 66, 66, 66, 66, 6, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 7, 66, 66, 66, 66, 66, 66, 66, 66, 5, 66, -1, 68, 70, 63, -1, -1, 67, 67, 67, 39, 67, 67, 67, 67, 43, 27, 67, 67, 67, 67, 67, 62, 67, 66, 66, 66, 66, 66, 66, 66, 66, 66, 18, 20, 27, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, -1, -1, 65, 61, 57, 67, 67, 40, 67, 67, 67, 67, 43, 67, 67, 67, 67, 62, 37, 66, 24, 66, 66, 66, 66, 66, 8, 66, 66, 66, 66, 66, 16, 66, 66, -1, 14, 66, 15, -1, 59, 67, 67, 34, 41, 28, 38, 67, 67, 67, 66, 66, 66, 66, 28, 66, 66, 23, 17, 66, 66, 0, 66, -1, 66, -1, 67, 67, 34, 33, 67, 67, 66, 66, 29, -1, 13, -1, -1, 66, 66, 22, 66, -1, 67, 67, 33, 67, 42, 21, -1, -1, -1, -1, 66, 19, 25, -1, 32, 35, 67, -1, -1, 26, 9, 66, 19, 60, 36, -1, 12, 66, 11, -1, -1, 10, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
